apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  labels:
    app: go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: goapp
        image: 542685624457.dkr.ecr.ap-south-1.amazonaws.com/goapp:v4
        ports:
        - containerPort: 8080
